package modelos.enums;

public enum Rubro {
    MEDICINA_PREPAGA,
    VIATICOS_MOBILIDAD,
    MANTENIMIENTO_MUEBLES_INSTALACIONES,
    LIBRERIA_OTROS_INSUMOS,
    PAPELERIA_IMPRESIONES,
    PRODUCTOS_DE_REVENTA
}
